### ISSUE TITLE
Uncaught TypeError: $(...).ifeed is not a function

### ISSUE THREAD

**Issue by vlafiser** [alisonmonteiro/ifeed#3]
I'm using same code like you at your example, but at Chrome is the issue like at the title is. Do you know what happened and how I can fix it, please?

Thanks!
Vlasti

**Comment by alisonmonteiro** [comment]
Hi, @vlafiser 

Sorry, but I've pushed some updates last week.
Now it's only 2kb gzipped.

Now you can use the same options, but using pure javascript elements. It should be like

```js
var opts = {
  // opts here
};

document.getElementById('ifeed').ifeed(opts)

// or

document.querySelectorAll('.my-element')[0].ifeed(opts);
```

See an example [here](https://github.com/alisonmonteiro/ifeed/blob/master/example/index.html)

**Comment by vlafiser** [comment]
Still doesn’t work man. Do you have any live preview?

Thanks!

**Comment by alisonmonteiro** [comment]
@vlafiser If you are using the example above, the error `Uncaught TypeError: $(...).ifeed is not a function` doesn't make sense, but I will check it.

And unfortunately instagram updated its API. 
Today I'll test this with the new API and update the ifeed docs asap.

If it's still working, I'll create a github page.

Thanks!

**Comment by vlafiser** [comment]
Thank you so much!

Do the DEMO please, because here on my side is any issue yet.

Thanks!
V.
